version: 2

models:
  - name: customer_segmentation_features
    description: User features for custormer segmentation
    columns:
      - name: user_id
        description: id from thelook_ecommerce.users
        tests:
          - unique
          - not_null
          
      - name: age
        description: age from thelook_ecommerce.users
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
          - not_null

      - name: country
        description: country from thelook_ecommerce.users
        tests:
          - not_null

      - name: state
        description: state from thelook_ecommerce.users
        tests:
          - not_null

      - name: nearest_distribution_center
        description: id from thelook_ecommerce.distribution_centers
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false
          - not_null

      - name: product_return_rate_last_year
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
          - not_null

      - name: customer_profit_level_last_year
        tests:
          - accepted_values:
              values: ['Level 1', 'Level 2', 'Level 3']
          - not_null

      - name: average_purchase_value
        description: The average value of purchases made by the customer in the past year
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
          - not_null
    
      - name: days_since_last_purchase
        description: The number of days since the customer's last purchase
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
          - not_null
    
      - name: purchase_frequency
        description: The number of purchases made by the customer in the past year, divided by the total number of days in the year
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
          - not_null

      - name: gender
        description: gender from thelook_ecommerce.users
        tests:
          - accepted_values:
              values: ['M', 'F']
          - not_null

      - name: traffic_source
        description: traffic source from thelook_ecommerce.users
        tests:
          - accepted_values:
              values: ['Search', 'Organic', 'Email', 'Facebook', 'Display']
          - not_null

      - name: profile_creation_timestamp
        description: profile creation timestamp from thelook_ecommerce.users
        tests:
          - not_null
