version: 2

models:
  - name: customer_segmentation_features
    description: User features for custormer segmentation
    columns:
      - name: user_id
        description: id from thelook_ecommerce.users
        tests:
          - unique
          - not_null
      - name: age
        description: age from thelook_ecommerce.users
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
          - not_null
      - name: country
        description: country from thelook_ecommerce.users
        tests:
          - not_null
      - name: state
        description: state from thelook_ecommerce.users
        tests:
          - not_null
      - name: nearest_distribution_center
        description: id from thelook_ecommerce.distribution_centers
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false
          - not_null
      - name: product_return_rate_last_year
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
          - not_null
      - name: customer_profit_level_last_year
        tests:
          - accepted_values:
              values: ['Level 1', 'Level 2', 'Level 3']
          - not_null